version: '3'

services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev

    ports:
      - "4000:3000"
    volumes:
      - /var/www/node_modules
      - .:/var/www
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /var/www/node_modules
      - .:/var/www
    command: ["npm", "run","test"]

          